const initstates = {
  enchants: [
    // **************************************************** //
    // Artifacts
    // **************************************************** //
    {
      name: "Anger Artifact",
      description: "Creates angry villager particles.",
      "maximum-level": 1,
      obtaining: {
        table: true,
        villager: true,
        loot: true,
      },
      rarity: "artifact",
      grindstoneable: true,
      targets: [
        "pickaxe",
        "sword",
        "axe",
        "elytra",
        "bow",
        "crossbow",
        "trident",
      ],
      conflicts: [],
      type: "artifact",
      enabled: false,
    },
    {
      name: "Ash Artifact",
      description: "Creates basalt deltas particles.",
      "maximum-level": 1,
      obtaining: {
        table: true,
        villager: true,
        loot: true,
      },
      rarity: "artifact",
      grindstoneable: true,
      targets: [
        "pickaxe",
        "sword",
        "axe",
        "elytra",
        "bow",
        "crossbow",
        "trident",
      ],
      conflicts: [],
      type: "artifact",
      enabled: false,
    },
    {
      name: "Clouds Artifact",
      description: "Creates cloud particles.",
      "maximum-level": 1,
      obtaining: {
        table: true,
        villager: true,
        loot: true,
      },
      rarity: "artifact",
      grindstoneable: true,
      targets: [
        "pickaxe",
        "sword",
        "axe",
        "elytra",
        "bow",
        "crossbow",
        "trident",
      ],
      conflicts: [],
      type: "artifact",
      enabled: false,
    },
    {
      name: "Copper Artifact",
      description: "Creates copper particles.",
      "maximum-level": 1,
      obtaining: {
        table: true,
        villager: true,
        loot: true,
      },
      rarity: "artifact",
      grindstoneable: true,
      targets: [
        "pickaxe",
        "sword",
        "axe",
        "elytra",
        "bow",
        "crossbow",
        "trident",
      ],
      conflicts: [],
      type: "artifact",
      enabled: false,
    },
    {
      name: "Crimson Artifact",
      description: "Creates crimson forest particles.",
      "maximum-level": 1,
      obtaining: {
        table: true,
        villager: true,
        loot: true,
      },
      rarity: "artifact",
      grindstoneable: true,
      targets: [
        "pickaxe",
        "sword",
        "axe",
        "elytra",
        "bow",
        "crossbow",
        "trident",
      ],
      conflicts: [],
      type: "artifact",
      enabled: false,
    },
    {
      name: "Damage Artifact",
      description: "Creates damage particles.",
      "maximum-level": 1,
      obtaining: {
        table: true,
        villager: true,
        loot: true,
      },
      rarity: "artifact",
      grindstoneable: true,
      targets: [
        "pickaxe",
        "sword",
        "axe",
        "elytra",
        "bow",
        "crossbow",
        "trident",
      ],
      conflicts: [],
      type: "artifact",
      enabled: false,
    },
    {
      name: "Dragon Artifact",
      description: "Creates dragon breath particles.",
      "maximum-level": 1,
      obtaining: {
        table: true,
        villager: true,
        loot: true,
      },
      rarity: "artifact",
      grindstoneable: true,
      targets: [
        "pickaxe",
        "sword",
        "axe",
        "elytra",
        "bow",
        "crossbow",
        "trident",
      ],
      conflicts: [],
      type: "artifact",
      enabled: false,
    },
    {
      name: "Dust Artifact",
      description: "Creates dust particles.",
      "maximum-level": 1,
      obtaining: {
        table: true,
        villager: true,
        loot: true,
      },
      rarity: "artifact",
      grindstoneable: true,
      targets: [
        "pickaxe",
        "sword",
        "axe",
        "elytra",
        "bow",
        "crossbow",
        "trident",
      ],
      conflicts: [],
      type: "artifact",
      enabled: false,
    },
    {
      name: "Emerald Artifact",
      description: "Creates emerald particles.",
      "maximum-level": 1,
      obtaining: {
        table: true,
        villager: true,
        loot: true,
      },
      rarity: "artifact",
      grindstoneable: true,
      targets: [
        "pickaxe",
        "sword",
        "axe",
        "elytra",
        "bow",
        "crossbow",
        "trident",
      ],
      conflicts: [],
      type: "artifact",
      enabled: false,
    },
    {
      name: "Enchantment Artifact",
      description: "Creates enchantment particles.",
      "maximum-level": 1,
      obtaining: {
        table: true,
        villager: true,
        loot: true,
      },
      rarity: "artifact",
      grindstoneable: true,
      targets: [
        "pickaxe",
        "sword",
        "axe",
        "elytra",
        "bow",
        "crossbow",
        "trident",
      ],
      conflicts: [],
      type: "artifact",
      enabled: false,
    },
    {
      name: "End Artifact",
      description: "Creates end rod particles.",
      "maximum-level": 1,
      obtaining: {
        table: true,
        villager: true,
        loot: true,
      },
      rarity: "artifact",
      grindstoneable: true,
      targets: [
        "pickaxe",
        "sword",
        "axe",
        "elytra",
        "bow",
        "crossbow",
        "trident",
      ],
      conflicts: [],
      type: "artifact",
      enabled: false,
    },
    {
      name: "Fire Artifact",
      description: "Creates fire particles.",
      "maximum-level": 1,
      obtaining: {
        table: true,
        villager: true,
        loot: true,
      },
      rarity: "artifact",
      grindstoneable: true,
      targets: [
        "pickaxe",
        "sword",
        "axe",
        "elytra",
        "bow",
        "crossbow",
        "trident",
      ],
      conflicts: [],
      type: "artifact",
      enabled: false,
    },
    {
      name: "Glow Artifact",
      description: "Creates glow particles.",
      "maximum-level": 1,
      obtaining: {
        table: true,
        villager: true,
        loot: true,
      },
      rarity: "artifact",
      grindstoneable: true,
      targets: [
        "pickaxe",
        "sword",
        "axe",
        "elytra",
        "bow",
        "crossbow",
        "trident",
      ],
      conflicts: [],
      type: "artifact",
      enabled: false,
    },
    {
      name: "Heart Artifact",
      description: "Creates heart particles.",
      "maximum-level": 1,
      obtaining: {
        table: true,
        villager: true,
        loot: true,
      },
      rarity: "artifact",
      grindstoneable: true,
      targets: [
        "pickaxe",
        "sword",
        "axe",
        "elytra",
        "bow",
        "crossbow",
        "trident",
      ],
      conflicts: [],
      type: "artifact",
      enabled: false,
    },
    {
      name: "Honey Artifact",
      description: "Creates dripping honey particles.",
      "maximum-level": 1,
      obtaining: {
        table: true,
        villager: true,
        loot: true,
      },
      rarity: "artifact",
      grindstoneable: true,
      targets: [
        "pickaxe",
        "sword",
        "axe",
        "elytra",
        "bow",
        "crossbow",
        "trident",
      ],
      conflicts: [],
      type: "artifact",
      enabled: false,
    },
    {
      name: "Ink Artifact",
      description: "Creates ink particles.",
      "maximum-level": 1,
      obtaining: {
        table: true,
        villager: true,
        loot: true,
      },
      rarity: "artifact",
      grindstoneable: true,
      targets: [
        "pickaxe",
        "sword",
        "axe",
        "elytra",
        "bow",
        "crossbow",
        "trident",
      ],
      conflicts: [],
      type: "artifact",
      enabled: false,
    },
    {
      name: "Lava Artifact",
      description: "Creates dripping lava particles.",
      "maximum-level": 1,
      obtaining: {
        table: true,
        villager: true,
        loot: true,
      },
      rarity: "artifact",
      grindstoneable: true,
      targets: [
        "pickaxe",
        "sword",
        "axe",
        "elytra",
        "bow",
        "crossbow",
        "trident",
      ],
      conflicts: [],
      type: "artifact",
      enabled: false,
    },
    {
      name: "Light Artifact",
      description: "Creates light particles.",
      "maximum-level": 1,
      obtaining: {
        table: true,
        villager: true,
        loot: true,
      },
      rarity: "artifact",
      grindstoneable: true,
      targets: [
        "pickaxe",
        "sword",
        "axe",
        "elytra",
        "bow",
        "crossbow",
        "trident",
      ],
      conflicts: [],
      type: "artifact",
      enabled: false,
    },
    {
      name: "Lime Artifact",
      description: "Creates lime particles.",
      "maximum-level": 1,
      obtaining: {
        table: true,
        villager: true,
        loot: true,
      },
      rarity: "artifact",
      grindstoneable: true,
      targets: [
        "pickaxe",
        "sword",
        "axe",
        "elytra",
        "bow",
        "crossbow",
        "trident",
      ],
      conflicts: [],
      type: "artifact",
      enabled: false,
    },
    {
      name: "Magic Artifact",
      description: "Creates magic particles.",
      "maximum-level": 1,
      obtaining: {
        table: true,
        villager: true,
        loot: true,
      },
      rarity: "artifact",
      grindstoneable: true,
      targets: [
        "pickaxe",
        "sword",
        "axe",
        "elytra",
        "bow",
        "crossbow",
        "trident",
      ],
      conflicts: [],
      type: "artifact",
      enabled: false,
    },
    {
      name: "Magma Artifact",
      description: "Creates lava pop particles.",
      "maximum-level": 1,
      obtaining: {
        table: true,
        villager: true,
        loot: true,
      },
      rarity: "artifact",
      grindstoneable: true,
      targets: [
        "pickaxe",
        "sword",
        "axe",
        "elytra",
        "bow",
        "crossbow",
        "trident",
      ],
      conflicts: [],
      type: "artifact",
      enabled: false,
    },
    {
      name: "Music Artifact",
      description: "Creates note particles.",
      "maximum-level": 1,
      obtaining: {
        table: true,
        villager: true,
        loot: true,
      },
      rarity: "artifact",
      grindstoneable: true,
      targets: [
        "pickaxe",
        "sword",
        "axe",
        "elytra",
        "bow",
        "crossbow",
        "trident",
      ],
      conflicts: [],
      type: "artifact",
      enabled: false,
    },
    {
      name: "Nautilus Artifact",
      description: "Creates nautilus particles.",
      "maximum-level": 1,
      obtaining: {
        table: true,
        villager: true,
        loot: true,
      },
      rarity: "artifact",
      grindstoneable: true,
      targets: [
        "pickaxe",
        "sword",
        "axe",
        "elytra",
        "bow",
        "crossbow",
        "trident",
      ],
      conflicts: [],
      type: "artifact",
      enabled: false,
    },
    {
      name: "Nether Artifact",
      description: "Creates nether portal particles.",
      "maximum-level": 1,
      obtaining: {
        table: true,
        villager: true,
        loot: true,
      },
      rarity: "artifact",
      grindstoneable: true,
      targets: [
        "pickaxe",
        "sword",
        "axe",
        "elytra",
        "bow",
        "crossbow",
        "trident",
      ],
      conflicts: [],
      type: "artifact",
      enabled: false,
    },
    {
      name: "Rain Artifact",
      description: "Creates rain particles.",
      "maximum-level": 1,
      obtaining: {
        table: true,
        villager: true,
        loot: true,
      },
      rarity: "artifact",
      grindstoneable: true,
      targets: [
        "pickaxe",
        "sword",
        "axe",
        "elytra",
        "bow",
        "crossbow",
        "trident",
      ],
      conflicts: [],
      type: "artifact",
      enabled: false,
    },
    {
      name: "Redstone Artifact",
      description: "Creates redstone particles.",
      "maximum-level": 1,
      obtaining: {
        table: true,
        villager: true,
        loot: true,
      },
      rarity: "artifact",
      grindstoneable: true,
      targets: [
        "pickaxe",
        "sword",
        "axe",
        "elytra",
        "bow",
        "crossbow",
        "trident",
      ],
      conflicts: [],
      type: "artifact",
      enabled: false,
    },
    {
      name: "Skulk Artifact",
      description: "Creates skulk vibration particles.",
      "maximum-level": 1,
      obtaining: {
        table: true,
        villager: true,
        loot: true,
      },
      rarity: "artifact",
      grindstoneable: true,
      targets: [
        "pickaxe",
        "sword",
        "axe",
        "elytra",
        "bow",
        "crossbow",
        "trident",
      ],
      conflicts: [],
      type: "artifact",
      enabled: false,
    },
    {
      name: "Slime Artifact",
      description: "Creates slime particles.",
      "maximum-level": 1,
      obtaining: {
        table: true,
        villager: true,
        loot: true,
      },
      rarity: "artifact",
      grindstoneable: true,
      targets: [
        "pickaxe",
        "sword",
        "axe",
        "elytra",
        "bow",
        "crossbow",
        "trident",
      ],
      conflicts: [],
      type: "artifact",
      enabled: false,
    },
    {
      name: "Smoke Artifact",
      description: "Creates smoke particles.",
      "maximum-level": 1,
      obtaining: {
        table: true,
        villager: true,
        loot: true,
      },
      rarity: "artifact",
      grindstoneable: true,
      targets: [
        "pickaxe",
        "sword",
        "axe",
        "elytra",
        "bow",
        "crossbow",
        "trident",
      ],
      conflicts: [],
      type: "artifact",
      enabled: true,
    },
    {
      name: "Snow Artifact",
      description: "Creates snow particles.",
      "maximum-level": 1,
      obtaining: {
        table: true,
        villager: true,
        loot: true,
      },
      rarity: "artifact",
      grindstoneable: true,
      targets: [
        "pickaxe",
        "sword",
        "axe",
        "elytra",
        "bow",
        "crossbow",
        "trident",
      ],
      conflicts: [],
      type: "artifact",
      enabled: false,
    },
    {
      name: "Soul Artifact",
      description: "Creates soul particles.",
      "maximum-level": 1,
      obtaining: {
        table: true,
        villager: true,
        loot: true,
      },
      rarity: "artifact",
      grindstoneable: true,
      targets: [
        "pickaxe",
        "sword",
        "axe",
        "elytra",
        "bow",
        "crossbow",
        "trident",
      ],
      conflicts: [],
      type: "artifact",
      enabled: false,
    },
    {
      name: "Soul Fire Artifact",
      description: "Creates soul flame particles.",
      "maximum-level": 1,
      obtaining: {
        table: true,
        villager: true,
        loot: true,
      },
      rarity: "artifact",
      grindstoneable: true,
      targets: [
        "pickaxe",
        "sword",
        "axe",
        "elytra",
        "bow",
        "crossbow",
        "trident",
      ],
      conflicts: [],
      type: "artifact",
      enabled: false,
    },
    {
      name: "Spark Artifact",
      description: "Creates spark particles.",
      "maximum-level": 1,
      obtaining: {
        table: true,
        villager: true,
        loot: true,
      },
      rarity: "artifact",
      grindstoneable: true,
      targets: [
        "pickaxe",
        "sword",
        "axe",
        "elytra",
        "bow",
        "crossbow",
        "trident",
      ],
      conflicts: [],
      type: "artifact",
      enabled: false,
    },
    {
      name: "Sparkle Artifact",
      description: "Creates firework particles.",
      "maximum-level": 1,
      obtaining: {
        table: true,
        villager: true,
        loot: true,
      },
      rarity: "artifact",
      grindstoneable: true,
      targets: [
        "pickaxe",
        "sword",
        "axe",
        "elytra",
        "bow",
        "crossbow",
        "trident",
      ],
      conflicts: [],
      type: "artifact",
      enabled: true,
    },
    {
      name: "Spore Artifact",
      description: "Creates dripleaf spore particles.",
      "maximum-level": 1,
      obtaining: {
        table: true,
        villager: true,
        loot: true,
      },
      rarity: "artifact",
      grindstoneable: true,
      targets: [
        "pickaxe",
        "sword",
        "axe",
        "elytra",
        "bow",
        "crossbow",
        "trident",
      ],
      conflicts: [],
      type: "artifact",
      enabled: false,
    },
    {
      name: "Sweep Artifact",
      description: "Creates sweep attack particles.",
      "maximum-level": 1,
      obtaining: {
        table: true,
        villager: true,
        loot: true,
      },
      rarity: "artifact",
      grindstoneable: true,
      targets: [
        "pickaxe",
        "sword",
        "axe",
        "elytra",
        "bow",
        "crossbow",
        "trident",
      ],
      conflicts: [],
      type: "artifact",
      enabled: false,
    },
    {
      name: "Tear Artifact",
      description: "Creates crying obsidian particles.",
      "maximum-level": 1,
      obtaining: {
        table: true,
        villager: true,
        loot: true,
      },
      rarity: "artifact",
      grindstoneable: true,
      targets: [
        "pickaxe",
        "sword",
        "axe",
        "elytra",
        "bow",
        "crossbow",
        "trident",
      ],
      conflicts: [],
      type: "artifact",
      enabled: false,
    },
    {
      name: "Totem Artifact",
      description: "Creates totem particles.",
      "maximum-level": 1,
      obtaining: {
        table: true,
        villager: true,
        loot: true,
      },
      rarity: "artifact",
      grindstoneable: true,
      targets: [
        "pickaxe",
        "sword",
        "axe",
        "elytra",
        "bow",
        "crossbow",
        "trident",
      ],
      conflicts: [],
      type: "artifact",
      enabled: false,
    },
    {
      name: "Villager Artifact",
      description: "Creates happy villager particles.",
      "maximum-level": 1,
      obtaining: {
        table: true,
        villager: true,
        loot: true,
      },
      rarity: "artifact",
      grindstoneable: true,
      targets: [
        "pickaxe",
        "sword",
        "axe",
        "elytra",
        "bow",
        "crossbow",
        "trident",
      ],
      conflicts: [],
      type: "artifact",
      enabled: false,
    },
    {
      name: "Warped Artifact",
      description: "Creates warped forest particles.",
      "maximum-level": 1,
      obtaining: {
        table: true,
        villager: true,
        loot: true,
      },
      rarity: "artifact",
      grindstoneable: true,
      targets: [
        "pickaxe",
        "sword",
        "axe",
        "elytra",
        "bow",
        "crossbow",
        "trident",
      ],
      conflicts: [],
      type: "artifact",
      enabled: false,
    },
    {
      name: "Water Artifact",
      description: "Creates dripping water particles.",
      "maximum-level": 1,
      obtaining: {
        table: true,
        villager: true,
        loot: true,
      },
      rarity: "artifact",
      grindstoneable: true,
      targets: [
        "pickaxe",
        "sword",
        "axe",
        "elytra",
        "bow",
        "crossbow",
        "trident",
      ],
      conflicts: [],
      type: "artifact",
      enabled: false,
    },
    {
      name: "Wax Artifact",
      description: "Creates wax particles.",
      "maximum-level": 1,
      obtaining: {
        table: true,
        villager: true,
        loot: true,
      },
      rarity: "artifact",
      grindstoneable: true,
      targets: [
        "pickaxe",
        "sword",
        "axe",
        "elytra",
        "bow",
        "crossbow",
        "trident",
      ],
      conflicts: [],
      type: "artifact",
      enabled: false,
    },
    {
      name: "Witch Artifact",
      description: "Creates witch particles.",
      "maximum-level": 1,
      obtaining: {
        table: true,
        villager: true,
        loot: true,
      },
      rarity: "artifact",
      grindstoneable: true,
      targets: [
        "pickaxe",
        "sword",
        "axe",
        "elytra",
        "bow",
        "crossbow",
        "trident",
      ],
      conflicts: [],
      type: "artifact",
      enabled: false,
    },
    {
      name: "Zap Artifact",
      description: "Creates electric particles.",
      "maximum-level": 1,
      obtaining: {
        table: true,
        villager: true,
        loot: true,
      },
      rarity: "artifact",
      grindstoneable: true,
      targets: [
        "pickaxe",
        "sword",
        "axe",
        "elytra",
        "bow",
        "crossbow",
        "trident",
      ],
      conflicts: [],
      type: "artifact",
      enabled: false,
    },
    // **************************************************** //
    // Curses
    // **************************************************** //
    {
      name: "Curse of Breaklessness",
      description: "Chance to prevent block breaking.",
      "maximum-level": 1,
      obtaining: {
        table: false,
        villager: true,
        loot: true,
      },
      rarity: "legendary",
      grindstoneable: true,
      targets: ["pickaxe", "axe", "hoe", "shovel"],
      conflicts: [],
      type: "curse",
      enabled: true,
    },
    {
      name: "Curse of Calling",
      description: "Angers all mobs within 20 blocks",
      "maximum-level": 1,
      obtaining: {
        table: false,
        villager: true,
        loot: true,
      },
      rarity: "legendary",
      grindstoneable: false,
      targets: ["helmet", "chestplate", "leggings", "boots"],
      conflicts: ["mending"],
      type: "curse",
      enabled: true,
    },
    {
      name: "Curse of Decay",
      description: "Automatically damages items when not held.",
      "maximum-level": 1,
      obtaining: {
        table: false,
        villager: true,
        loot: true,
      },
      rarity: "legendary",
      grindstoneable: true,
      targets: ["all"],
      conflicts: ["mending", "repairing"],
      type: "curse",
      enabled: true,
    },
    {
      name: "Curse of Fragility",
      description: "Decreases item durability times.",
      "maximum-level": 1,
      obtaining: {
        table: false,
        villager: true,
        loot: true,
      },
      rarity: "legendary",
      grindstoneable: false,
      targets: ["all"],
      conflicts: ["unbreaking"],
      type: "curse",
      enabled: true,
    },
    {
      name: "Curse of Harmlessness",
      description: "Chance for attacks to do nothing.",
      "maximum-level": 1,
      obtaining: {
        table: false,
        villager: true,
        loot: true,
      },
      rarity: "legendary",
      grindstoneable: false,
      targets: ["sword", "axe"],
      conflicts: [],
      type: "curse",
      enabled: true,
    },
    {
      name: "Curse of Hunger",
      description: "Increases hunger loss.",
      "maximum-level": 1,
      obtaining: {
        table: false,
        villager: true,
        loot: true,
      },
      rarity: "legendary",
      grindstoneable: false,
      targets: ["helmet"],
      conflicts: ["sating"],
      type: "curse",
      enabled: true,
    },
    {
      name: "Curse of Inaccuracy",
      description: "Arrows fire incorrectly.",
      "maximum-level": 1,
      obtaining: {
        table: false,
        villager: true,
        loot: true,
      },
      rarity: "legendary",
      grindstoneable: true,
      targets: ["bow"],
      conflicts: [],
      type: "curse",
      enabled: true,
    },
    {
      name: "Curse of Misfortune",
      description: "Chance for blocks to not drop items.",
      "maximum-level": 1,
      obtaining: {
        table: false,
        villager: true,
        loot: true,
      },
      rarity: "legendary",
      grindstoneable: true,
      targets: ["pickaxe", "axe", "hoe", "shovel"],
      conflicts: ["fortune"],
      type: "curse",
      enabled: true,
    },
    {
      name: "Curse of Permanence",
      description: "Prevents item from being modified in an anvil.",
      "maximum-level": 1,
      obtaining: {
        table: false,
        villager: true,
        loot: true,
      },
      rarity: "legendary",
      grindstoneable: false,
      targets: ["all"],
      conflicts: ["mending"],
      type: "curse",
      enabled: true,
    },
    // **************************************************** //
    // Normal
    // **************************************************** //
    {
      name: "Abattoir",
      description: "Increases damage against passive mobs.",
      "maximum-level": 5,
      obtaining: {
        table: true,
        villager: true,
        loot: true,
      },
      rarity: "common",
      grindstoneable: true,
      targets: ["trident"],
      conflicts: [
        "serrated",
        "bladed",
        "phantasm",
        "pacify",
        "arachnid",
        "impaling",
      ],
      type: "normal",
      enabled: true,
    },
    {
      name: "Abrasion",
      description: "Damages your opponents armor.",
      "maximum-level": 2,
      obtaining: {
        table: true,
        villager: true,
        loot: true,
      },
      rarity: "legendary",
      grindstoneable: true,
      targets: ["sword", "axe"],
      conflicts: [],
      type: "normal",
      enabled: true,
    },
    {
      name: "Aerial",
      description: "Increases arrow damage when shot while in air.",
      "maximum-level": 3,
      obtaining: {
        table: true,
        villager: true,
        loot: true,
      },
      rarity: "epic",
      grindstoneable: true,
      targets: ["bow", "crossbow"],
      conflicts: [],
      type: "normal",
      enabled: true,
    },
    {
      name: "Aquatic",
      description: "Trident deals more damage when shot from water.",
      "maximum-level": 8,
      obtaining: {
        table: true,
        villager: true,
        loot: true,
      },
      rarity: "rare",
      grindstoneable: true,
      targets: ["trident"],
      conflicts: [],
      type: "normal",
      enabled: true,
    },
    {
      name: "Arachnid",
      description: "Increases damage against spiders .",
      "maximum-level": 5,
      obtaining: {
        table: true,
        villager: true,
        loot: true,
      },
      rarity: "common",
      grindstoneable: true,
      targets: ["trident"],
      conflicts: [
        "serrated",
        "bladed",
        "phantasm",
        "pacify",
        "abattoir",
        "impaling",
      ],
      type: "normal",
      enabled: true,
    },
    {
      name: "Arborist",
      description: "Get more sticks, apples, and saplings from leaves.",
      "maximum-level": 4,
      obtaining: {
        table: true,
        villager: true,
        loot: true,
      },
      rarity: "rare",
      grindstoneable: true,
      targets: ["axe", "shears"],
      conflicts: ["silk_touch"],
      type: "normal",
      enabled: true,
    },
    {
      name: "Arcanic",
      description: "Chance to ignore potion damage.",
      "maximum-level": 6,
      obtaining: {
        table: true,
        villager: true,
        loot: true,
      },
      rarity: "epic",
      grindstoneable: true,
      targets: ["helmet", "chestplate", "leggings", "boots"],
      conflicts: [],
      type: "normal",
      enabled: true,
    },
    {
      name: "Atmospheric",
      description: "Increases trident damage when you are in air.",
      "maximum-level": 3,
      obtaining: {
        table: true,
        villager: true,
        loot: true,
      },
      rarity: "epic",
      grindstoneable: true,
      targets: ["trident"],
      conflicts: [],
      type: "normal",
      enabled: true,
    },
    {
      name: "Backstab",
      description: "Deal more damage from behind.",
      "maximum-level": 3,
      obtaining: {
        table: true,
        villager: true,
        loot: true,
      },
      rarity: "rare",
      grindstoneable: true,
      targets: ["sword", "axe"],
      conflicts: [],
      type: "normal",
      enabled: true,
    },
    {
      name: "Beheading",
      description: "Chance of getting player or mob head.",
      "maximum-level": 3,
      obtaining: {
        table: true,
        villager: true,
        loot: true,
      },
      rarity: "uncommon",
      grindstoneable: true,
      targets: ["sword", "axe"],
      conflicts: [],
      type: "normal",
      enabled: true,
    },
    {
      name: "Blast Mining",
      description: "Mines blocks in a 3x3 area.",
      "maximum-level": 3,
      obtaining: {
        table: true,
        villager: true,
        loot: true,
      },
      rarity: "legendary",
      grindstoneable: true,
      targets: ["pickaxe"],
      conflicts: ["drill", "vein"],
      type: "normal",
      enabled: false,
    },
    {
      name: "Bleed",
      description:
        "Chance to cause your opponent to bleed, damaging them repeatedly.",
      "maximum-level": 7,
      obtaining: {
        table: true,
        villager: true,
        loot: true,
      },
      rarity: "legendary",
      grindstoneable: true,
      targets: ["sword"],
      conflicts: [],
      type: "normal",
      enabled: true,
    },
    {
      name: "Blind",
      description: "Chance of blinding your opponent.",
      "maximum-level": 6,
      obtaining: {
        table: true,
        villager: true,
        loot: true,
      },
      rarity: "legendary",
      grindstoneable: true,
      targets: ["bow", "crossbow"],
      conflicts: [],
      type: "normal",
      enabled: true,
    },
    {
      name: "Block Breather",
      description: "Chance to ignore suffocation damage.",
      "maximum-level": 3,
      obtaining: {
        table: true,
        villager: true,
        loot: true,
      },
      rarity: "rare",
      grindstoneable: true,
      targets: ["helmet"],
      conflicts: [],
      type: "normal",
      enabled: true,
    },
    {
      name: "Boss Hunter",
      description: "Increases damage against bosses.",
      "maximum-level": 8,
      obtaining: {
        table: true,
        villager: true,
        loot: true,
      },
      rarity: "rare",
      grindstoneable: true,
      targets: ["bow", "crossbow"],
      conflicts: [],
      type: "normal",
      enabled: true,
    },
    {
      name: "Buckshot",
      description: "Shoots multiple arrows spread out.",
      "maximum-level": 2,
      obtaining: {
        table: true,
        villager: true,
        loot: true,
      },
      rarity: "legendary",
      grindstoneable: true,
      targets: ["bow"],
      conflicts: ["succession", "pentashot", "tripleshot"],
      type: "normal",
      enabled: true,
    },
    {
      name: "Butchering",
      description: "Increases damage against passive mobs.",
      "maximum-level": 5,
      obtaining: {
        table: true,
        villager: true,
        loot: true,
      },
      rarity: "common",
      grindstoneable: true,
      targets: ["sword", "axe"],
      conflicts: [
        "sharpness",
        "bane_of_arthropods",
        "smite",
        "defusion",
        "razor",
        "ender_slayer",
      ],
      type: "normal",
      enabled: true,
    },
    {
      name: "Cerebral",
      description: "Increases damage on headshots.",
      "maximum-level": 8,
      obtaining: {
        table: true,
        villager: true,
        loot: true,
      },
      rarity: "rare",
      grindstoneable: true,
      targets: ["bow", "crossbow"],
      conflicts: [],
      type: "normal",
      enabled: true,
    },
    {
      name: "Chopless",
      description: "Reduces damage dealt by axes.",
      "maximum-level": 6,
      obtaining: {
        table: true,
        villager: true,
        loot: true,
      },
      rarity: "rare",
      grindstoneable: true,
      targets: ["helmet", "chestplate", "leggings", "boots"],
      conflicts: [],
      type: "normal",
      enabled: true,
    },
    {
      name: "Cleave",
      description: "Damage all entities around attacked entity.",
      "maximum-level": 8,
      obtaining: {
        table: true,
        villager: true,
        loot: true,
      },
      rarity: "rare",
      grindstoneable: true,
      targets: ["axe"],
      conflicts: ["carve"],
      type: "normal",
      enabled: true,
    },
    {
      name: "Collateral",
      description: "Arrows can go through entities.",
      "maximum-level": 4,
      obtaining: {
        table: true,
        villager: true,
        loot: true,
      },
      rarity: "rare",
      grindstoneable: true,
      targets: ["bow"],
      conflicts: [],
      type: "normal",
      enabled: true,
    },
    {
      name: "Conclude",
      description: "Chance to instantly kill entities on low health.",
      "maximum-level": 5,
      obtaining: {
        table: true,
        villager: true,
        loot: true,
      },
      rarity: "epic",
      grindstoneable: true,
      targets: ["trident"],
      conflicts: [],
      type: "normal",
      enabled: true,
    },
    {
      name: "Corrosive",
      description: "Damages your opponents armor.",
      "maximum-level": 2,
      obtaining: {
        table: true,
        villager: true,
        loot: true,
      },
      rarity: "legendary",
      grindstoneable: true,
      targets: ["bow", "crossbow"],
      conflicts: [],
      type: "normal",
      enabled: true,
    },
    {
      name: "Cranial",
      description: "Increases damage on headshots.",
      "maximum-level": 8,
      obtaining: {
        table: true,
        villager: true,
        loot: true,
      },
      rarity: "rare",
      grindstoneable: true,
      targets: ["trident"],
      conflicts: [],
      type: "normal",
      enabled: true,
    },
    {
      name: "Criticals",
      description: "Increases critical damage .",
      "maximum-level": 3,
      obtaining: {
        table: true,
        villager: true,
        loot: true,
      },
      rarity: "epic",
      grindstoneable: true,
      targets: ["sword", "axe"],
      conflicts: [],
      type: "normal",
      enabled: true,
    },
    {
      name: "Cubism",
      description: "Increases damage dealt against slimes and magma cubes.",
      "maximum-level": 7,
      obtaining: {
        table: true,
        villager: true,
        loot: true,
      },
      rarity: "rare",
      grindstoneable: true,
      targets: ["sword", "axe"],
      conflicts: [],
      type: "normal",
      enabled: true,
    },
    {
      name: "Defender",
      description: "Prevents damaging your own pets.",
      "maximum-level": 1,
      obtaining: {
        table: true,
        villager: true,
        loot: true,
      },
      rarity: "uncommon",
      grindstoneable: true,
      targets: ["bow", "crossbow"],
      conflicts: [],
      type: "normal",
      enabled: true,
    },
    {
      name: "Deflection",
      description: "Rebounds some incoming damage back to your attacker.",
      "maximum-level": 6,
      obtaining: {
        table: true,
        villager: true,
        loot: true,
      },
      rarity: "uncommon",
      grindstoneable: true,
      targets: ["shield"],
      conflicts: [],
      type: "normal",
      enabled: true,
    },
    {
      name: "Defusion",
      description: "Increases damage against creepers.",
      "maximum-level": 5,
      obtaining: {
        table: true,
        villager: true,
        loot: true,
      },
      rarity: "common",
      grindstoneable: true,
      targets: ["sword", "axe"],
      conflicts: [
        "sharpness",
        "bane_of_arthropods",
        "smite",
        "butchering",
        "razor",
        "ender_slayer",
        "introversion",
      ],
      type: "normal",
      enabled: true,
    },
    {
      name: "Dexterous",
      description: "Increases attack speed.",
      "maximum-level": 2,
      obtaining: {
        table: true,
        villager: true,
        loot: true,
      },
      rarity: "epic",
      grindstoneable: true,
      targets: ["sword", "axe"],
      conflicts: [],
      type: "normal",
      enabled: true,
    },
    {
      name: "Disable",
      description: "Chance of giving your opponent extreme mining fatigue.",
      "maximum-level": 3,
      obtaining: {
        table: true,
        villager: true,
        loot: true,
      },
      rarity: "epic",
      grindstoneable: true,
      targets: ["axe"],
      conflicts: [],
      type: "normal",
      enabled: false,
    },
    {
      name: "Disappear",
      description: "Go invisble if damaged on low health.",
      "maximum-level": 6,
      obtaining: {
        table: true,
        villager: true,
        loot: true,
      },
      rarity: "legendary",
      grindstoneable: true,
      targets: ["helmet", "chestplate", "leggings", "boots"],
      type: "normal",
      enabled: true,
      conflicts: [],
    },
    {
      name: "Diurnal",
      description: "Increases damage dealt at daytime.",
      "maximum-level": 6,
      obtaining: {
        table: true,
        villager: true,
        loot: true,
      },
      rarity: "rare",
      grindstoneable: true,
      targets: ["sword"],
      conflicts: ["nocturnal"],
      type: "normal",
      enabled: true,
    },
    {
      name: "Diverse",
      description: "Increases damage dealt against players holding swords.",
      "maximum-level": 6,
      obtaining: {
        table: true,
        villager: true,
        loot: true,
      },
      rarity: "rare",
      grindstoneable: true,
      targets: ["axe"],
      conflicts: [],
      type: "normal",
      enabled: true,
    },
    {
      name: "Dousing",
      description: "Chance to put out fire on block.",
      "maximum-level": 8,
      obtaining: {
        table: true,
        villager: true,
        loot: true,
      },
      rarity: "legendary",
      grindstoneable: true,
      targets: ["bow", "crossbow"],
      conflicts: ["ignite"],
      type: "normal",
      enabled: true,
    },
    {
      name: "Drill",
      description: "Mines blocks behind other blocks.",
      "maximum-level": 5,
      obtaining: {
        table: true,
        villager: true,
        loot: true,
      },
      rarity: "legendary",
      grindstoneable: true,
      targets: ["pickaxe", "axe", "shovel"],
      conflicts: ["lumberjack", "blast_mining", "vein"],
      type: "normal",
      enabled: false,
    },
    {
      name: "Dullness",
      description: "Chance of giving your opponent weakness.",
      "maximum-level": 3,
      obtaining: {
        table: true,
        villager: true,
        loot: true,
      },
      rarity: "epic",
      grindstoneable: true,
      targets: ["sword"],
      conflicts: [],
      type: "normal",
      enabled: true,
    },
    {
      name: "Dweller",
      description: "Increases damage against illagers.",
      "maximum-level": 3,
      obtaining: {
        table: true,
        villager: true,
        loot: true,
      },
      rarity: "rare",
      grindstoneable: true,
      targets: ["sword", "axe"],
      conflicts: [],
      type: "normal",
      enabled: true,
    },
    {
      name: "Economical",
      description: "Chance to not consume fireworks while boosting.",
      "maximum-level": 4,
      obtaining: {
        table: true,
        villager: true,
        loot: true,
      },
      rarity: "epic",
      grindstoneable: true,
      targets: ["elytra"],
      conflicts: [],
      type: "normal",
      enabled: true,
    },
    {
      name: "Electroshock",
      description: "Chance to strike lightning on your attacker.",
      "maximum-level": 3,
      obtaining: {
        table: true,
        villager: true,
        loot: true,
      },
      rarity: "rare",
      grindstoneable: true,
      targets: ["shield"],
      conflicts: [],
      type: "normal",
      enabled: false,
    },
    {
      name: "Enderism",
      description: "Increases damage dealt in the end.",
      "maximum-level": 6,
      obtaining: {
        table: true,
        villager: true,
        loot: true,
      },
      rarity: "epic",
      grindstoneable: true,
      targets: ["bow", "crossbow"],
      conflicts: ["netheric"],
      type: "normal",
      enabled: true,
    },
    {
      name: "Ender Slayer",
      description: "Increases damage against end mobs.",
      "maximum-level": 5,
      obtaining: {
        table: true,
        villager: true,
        loot: true,
      },
      rarity: "common",
      grindstoneable: true,
      targets: ["sword", "axe"],
      conflicts: [
        "sharpness",
        "bane_of_arthropods",
        "smite",
        "defusion",
        "razor",
        "butchering",
        "introversion",
      ],
      type: "normal",
      enabled: true,
    },
    {
      name: "End Infusion",
      description: "Increases damage dealt in the end.",
      "maximum-level": 6,
      obtaining: {
        table: true,
        villager: true,
        loot: true,
      },
      rarity: "epic",
      grindstoneable: true,
      targets: ["sword"],
      conflicts: ["nether_infusion"],
      type: "normal",
      enabled: true,
    },
    {
      name: "Evasion",
      description: "Chance to ignore incoming damage.",
      "maximum-level": 3,
      obtaining: {
        table: true,
        villager: true,
        loot: true,
      },
      rarity: "epic",
      grindstoneable: true,
      targets: ["helmet", "chestplate", "leggings", "boots"],
      conflicts: [],
      type: "normal",
      enabled: true,
    },
    {
      name: "Extinguishing",
      description: "Chance to remove fire when taking fire damage.",
      "maximum-level": 3,
      obtaining: {
        table: true,
        villager: true,
        loot: true,
      },
      rarity: "epic",
      grindstoneable: true,
      targets: ["helmet", "chestplate", "leggings", "boots"],
      conflicts: [],
      type: "normal",
      enabled: true,
    },
    {
      name: "Extract",
      description: "Heals a portion of damage dealt.",
      "maximum-level": 3,
      obtaining: {
        table: true,
        villager: true,
        loot: true,
      },
      rarity: "epic",
      grindstoneable: true,
      targets: ["trident"],
      conflicts: [],
      type: "normal",
      enabled: true,
    },
    {
      name: "Famine",
      description: "Chance of giving your opponent hunger.",
      "maximum-level": 8,
      obtaining: {
        table: true,
        villager: true,
        loot: true,
      },
      rarity: "rare",
      grindstoneable: true,
      targets: ["sword"],
      conflicts: [],
      enabled: true,
    },
    {
      name: "Farmhand",
      description: "Till blocks around initial block.",
      "maximum-level": 2,
      obtaining: {
        table: true,
        villager: true,
        loot: true,
      },
      rarity: "rare",
      grindstoneable: true,
      targets: ["hoe"],
      conflicts: [],
      enabled: true,
    },
    {
      name: "Fetching",
      description:
        "Drops and xp from wolf kills go directly into your inventory.",
      "maximum-level": 1,
      obtaining: {
        table: true,
        villager: true,
        loot: true,
      },
      rarity: "rare",
      grindstoneable: true,
      targets: ["helmet"],
      conflicts: [],
      enabled: true,
    },
    {
      name: "Finality",
      description: "Chance to instantly kill entities on low health.",
      "maximum-level": 5,
      obtaining: {
        table: true,
        villager: true,
        loot: true,
      },
      rarity: "epic",
      grindstoneable: true,
      targets: ["bow"],
      conflicts: [],
      enabled: true,
    },
    {
      name: "Finishing",
      description: "Chance to instantly kill entities on low health.",
      "maximum-level": 5,
      obtaining: {
        table: true,
        villager: true,
        loot: true,
      },
      rarity: "epic",
      grindstoneable: true,
      targets: ["sword"],
      conflicts: [],
      enabled: true,
    },
    {
      name: "Fire Affinity",
      description: "Increases damage dealt when on fire.",
      "maximum-level": 7,
      obtaining: {
        table: true,
        villager: true,
        loot: true,
      },
      rarity: "epic",
      targets: ["sword"],
      grindstoneable: true,
      conflicts: ["water_affinity"],
      enabled: true,
    },
    {
      name: "First Strike",
      description: "Increases damage dealt when entity is on max health.",
      "maximum-level": 5,
      obtaining: {
        table: true,
        villager: true,
        loot: true,
      },
      rarity: "rare",
      targets: ["sword"],
      grindstoneable: true,
      conflicts: [],
      enabled: true,
    },
    {
      name: "Flinch",
      description: "Chance to blind your attacker.",
      "maximum-level": 6,
      obtaining: {
        table: true,
        villager: true,
        loot: true,
      },
      rarity: "rare",
      grindstoneable: true,
      targets: ["shield"],
      conflicts: [],
      enabled: true,
    },
    {
      name: "Forcefield",
      description: "Damages all nearby monsters.",
      "maximum-level": 2,
      obtaining: {
        table: true,
        villager: true,
        loot: true,
      },
      rarity: "legendary",
      grindstoneable: true,
      targets: ["helmet", "chestplate", "leggings", "boots"],
      conflicts: [],
      enabled: true,
    },
    {
      name: "Freerunner",
      description: "Chance to ignore fall damage.",
      "maximum-level": 6,
      obtaining: {
        table: true,
        villager: true,
        loot: true,
      },
      rarity: "epic",
      grindstoneable: true,
      targets: ["boots"],
      conflicts: [],
      enabled: true,
    },
    {
      name: "Frozen",
      description: "Chance to give your attacker slowness.",
      "maximum-level": 6,
      obtaining: {
        table: true,
        villager: true,
        loot: true,
      },
      rarity: "epic",
      grindstoneable: true,
      targets: ["helmet", "chestplate", "leggings", "boots"],
      conflicts: [],
      enabled: true,
    },
    {
      name: "Fury",
      description: "Chance of angering nearby monsters towards your opponent.",
      "maximum-level": 7,
      obtaining: {
        table: true,
        villager: true,
        loot: true,
      },
      rarity: "rare",
      grindstoneable: true,
      targets: ["sword"],
      conflicts: [],
      enabled: false,
    },
    {
      name: "Goliath",
      description:
        "Increases damage against entities with more health than you.",
      "maximum-level": 8,
      obtaining: {
        table: true,
        villager: true,
        loot: true,
      },
      rarity: "rare",
      grindstoneable: true,
      targets: ["sword"],
      conflicts: [],
      enabled: true,
    },
    {
      name: "Graceful",
      description:
        "Chance of getting slow falling just above hitting the ground.",
      "maximum-level": 6,
      obtaining: {
        table: true,
        villager: true,
        loot: true,
      },
      rarity: "legendary",
      grindstoneable: true,
      targets: ["boots"],
      conflicts: [],
      enabled: true,
    },
    {
      name: "Grapple",
      description: "Pulls entities towards you.",
      "maximum-level": 2,
      obtaining: {
        table: true,
        villager: true,
        loot: true,
      },
      rarity: "epic",
      grindstoneable: true,
      targets: ["sword", "axe"],
      conflicts: ["knockback", "tornado", "annihilate"],
      enabled: true,
    },
    {
      name: "Green Thumb",
      description: "Left clicking dirt turns it to grass.",
      "maximum-level": 1,
      obtaining: {
        table: true,
        villager: true,
        loot: true,
      },
      rarity: "rare",
      grindstoneable: true,
      targets: ["hoe"],
      conflicts: [],
      enabled: true,
    },
    {
      name: "Grit",
      description: "Damages your opponents weapon.",
      "maximum-level": 3,
      obtaining: {
        table: true,
        villager: true,
        loot: true,
      },
      rarity: "epic",
      grindstoneable: true,
      targets: ["helmet", "chestplate", "leggings", "boots"],
      conflicts: [],
      enabled: true,
    },
    {
      name: "Hellish",
      description: "Increases damage dealt in the nether.",
      "maximum-level": 6,
      obtaining: {
        table: true,
        villager: true,
        loot: true,
      },
      rarity: "epic",
      grindstoneable: true,
      targets: ["trident"],
      conflicts: ["void_affinity"],
      enabled: true,
    },
    {
      name: "Hook",
      description: "Pulls entities towards you.",
      "maximum-level": 2,
      obtaining: {
        table: true,
        villager: true,
        loot: true,
      },
      rarity: "epic",
      grindstoneable: true,
      targets: ["bow"],
      conflicts: ["punch"],
      enabled: true,
    },
    {
      name: "Horde",
      description: "Increases damage dealt the more mobs are nearby.",
      "maximum-level": 4,
      obtaining: {
        table: true,
        villager: true,
        loot: true,
      },
      rarity: "epic",
      grindstoneable: true,
      targets: ["sword"],
      conflicts: [],
      enabled: true,
    },
    {
      name: "Ice Shot",
      description: "Chance of freezing your opponent.",
      "maximum-level": 3,
      obtaining: {
        table: true,
        villager: true,
        loot: true,
      },
      rarity: "epic",
      grindstoneable: true,
      targets: ["bow", "crossbow"],
      conflicts: [],
      enabled: true,
    },
    {
      name: "Identify",
      description: "Chance to give your attacker glowing.",
      "maximum-level": 2,
      obtaining: {
        table: true,
        villager: true,
        loot: true,
      },
      rarity: "epic",
      grindstoneable: true,
      targets: ["shield"],
      conflicts: [],
      enabled: false,
    },
    {
      name: "Ignite",
      description: "Chance to light hit block on fire.",
      "maximum-level": 8,
      obtaining: {
        table: true,
        villager: true,
        loot: true,
      },
      rarity: "legendary",
      grindstoneable: true,
      targets: ["bow", "crossbow"],
      conflicts: ["dousing"],
      enabled: true,
    },
    {
      name: "Illusion Aspect",
      description: "Chance to blind and nauseate opponent.",
      "maximum-level": 2,
      obtaining: {
        table: true,
        villager: true,
        loot: true,
      },
      rarity: "legendary",
      grindstoneable: true,
      targets: ["sword"],
      conflicts: [],
      enabled: true,
    },
    {
      name: "Impact",
      description: "Chance to deal extreme damage.",
      "maximum-level": 3,
      obtaining: {
        table: true,
        villager: true,
        loot: true,
      },
      rarity: "legendary",
      grindstoneable: true,
      targets: ["trident"],
      conflicts: [],
      enabled: true,
    },
    {
      name: "Incandescence",
      description: "Light your attacker on fire.",
      "maximum-level": 2,
      obtaining: {
        table: true,
        villager: true,
        loot: true,
      },
      rarity: "epic",
      grindstoneable: true,
      targets: ["helmet", "chestplate", "leggings", "boots"],
      conflicts: [],
      enabled: true,
    },
    {
      name: "Infernal Touch",
      description: "Automatically smelt mined blocks.",
      "maximum-level": 1,
      obtaining: {
        table: true,
        villager: true,
        loot: true,
      },
      rarity: "rare",
      grindstoneable: true,
      targets: ["pickaxe"],
      conflicts: ["silk_touch", "stone_switcher"],
      enabled: true,
    },
    {
      name: "Inferno",
      description: "Flaming tridents.",
      "maximum-level": 1,
      obtaining: {
        table: true,
        villager: true,
        loot: true,
      },
      rarity: "uncommon",
      grindstoneable: true,
      targets: ["trident"],
      conflicts: [],
      enabled: true,
    },
    {
      name: "Infuriate",
      description: "Chance to cause nearby mobs to attack your opponent.",
      "maximum-level": 7,
      obtaining: {
        table: true,
        villager: true,
        loot: true,
      },
      rarity: "epic",
      grindstoneable: true,
      targets: ["shield"],
      conflicts: [],
      enabled: true,
    },
    {
      name: "Insecticide",
      description: "Increases damage against spiders.",
      "maximum-level": 5,
      obtaining: {
        table: true,
        villager: true,
        loot: true,
      },
      rarity: "common",
      grindstoneable: true,
      targets: ["bow"],
      conflicts: ["power", "force", "revenant", "slaughter", "settle"],
      enabled: true,
    },
    {
      name: "Instantaneous",
      description: "Chance to instantly break blocks.",
      "maximum-level": 7,
      obtaining: {
        table: true,
        villager: true,
        loot: true,
      },
      rarity: "rare",
      grindstoneable: true,
      targets: ["pickaxe", "axe", "shovel", "hoe"],
      conflicts: [],
      enabled: true,
    },
    {
      name: "Introversion",
      description: "Increases damage against players.",
      "maximum-level": 5,
      obtaining: {
        table: true,
        villager: true,
        loot: true,
      },
      rarity: "uncommon",
      grindstoneable: true,
      targets: ["sword", "axe"],
      conflicts: [
        "sharpness",
        "bane_of_arthropods",
        "smite",
        "defusion",
        "razor",
        "ender_slayer",
        "butchering",
      ],
      enabled: true,
    },
    {
      name: "Invigoration",
      description:
        "Increases outgoing damage and reduces incoming damage when low on health.",
      "maximum-level": 3,
      obtaining: {
        table: true,
        villager: true,
        loot: true,
      },
      rarity: "epic",
      grindstoneable: true,
      targets: ["helmet", "chestplate", "leggings", "boots"],
      conflicts: [],
      enabled: true,
    },
    {
      name: "Kinetic",
      description: "Reduces damage taken when flying into a wall.",
      "maximum-level": 6,
      obtaining: {
        table: true,
        villager: true,
        loot: true,
      },
      rarity: "rare",
      grindstoneable: true,
      targets: ["elytra"],
      conflicts: [],
      enabled: true,
    },
    {
      name: "Launch",
      description: "Fireworks give a short burst of extreme speed.",
      "maximum-level": 8,
      obtaining: {
        table: true,
        villager: true,
        loot: true,
      },
      rarity: "epic",
      grindstoneable: true,
      targets: ["elytra"],
      conflicts: [],
      enabled: true,
    },
    {
      name: "Leeching",
      description: "Heals a portion of damage dealt.",
      "maximum-level": 3,
      obtaining: {
        table: true,
        villager: true,
        loot: true,
      },
      rarity: "epic",
      grindstoneable: true,
      targets: ["sword", "axe"],
      conflicts: ["life_steal"],
      enabled: true,
    },
    {
      name: "Lesion",
      description:
        "Chance to your opponent to bleed, damaging them repeatedly.",
      "maximum-level": 7,
      obtaining: {
        table: true,
        villager: true,
        loot: true,
      },
      rarity: "legendary",
      grindstoneable: true,
      targets: ["trident"],
      conflicts: [],
      enabled: true,
    },
    {
      name: "Levitate",
      description: "Chance of applying levitation to your opponent.",
      "maximum-level": 2,
      obtaining: {
        table: true,
        villager: true,
        loot: true,
      },
      rarity: "legendary",
      grindstoneable: true,
      targets: ["bow", "crossbow"],
      conflicts: [],
      enabled: true,
    },
    {
      name: "Liquid Shot",
      description: "Increases damage against fiery mobs.",
      "maximum-level": 5,
      obtaining: {
        table: true,
        villager: true,
        loot: true,
      },
      rarity: "rare",
      grindstoneable: true,
      targets: ["bow", "crossbow"],
      conflicts: [],
      enabled: true,
    },
    {
      name: "Lucky Catch",
      description: "Chance to double fishing drops.",
      "maximum-level": 3,
      obtaining: {
        table: true,
        villager: true,
        loot: true,
      },
      rarity: "legendary",
      grindstoneable: true,
      targets: ["rod"],
      conflicts: [],
      enabled: true,
    },
    {
      name: "Lumberjack",
      description: "Instantly cut down entire trees.",
      "maximum-level": 6,
      obtaining: {
        table: true,
        villager: true,
        loot: true,
      },
      rarity: "legendary",
      grindstoneable: true,
      targets: ["axe"],
      conflicts: ["drill"],
      enabled: true,
    },
    {
      name: "Magnetic",
      description: "Items and XP go towards you.",
      "maximum-level": 4,
      obtaining: {
        table: true,
        villager: true,
        loot: true,
      },
      rarity: "epic",
      grindstoneable: true,
      targets: ["boots"],
      conflicts: [],
      enabled: true,
    },
    {
      name: "Marking",
      description: "Increases subsequent damage dealt to opponent.",
      "maximum-level": 4,
      obtaining: {
        table: true,
        villager: true,
        loot: true,
      },
      rarity: "legendary",
      grindstoneable: true,
      targets: ["bow", "crossbow"],
      conflicts: [],
      enabled: true,
    },
    {
      name: "Marksman",
      description: "Removes arrow drop.",
      "maximum-level": 4,
      obtaining: {
        table: true,
        villager: true,
        loot: true,
      },
      rarity: "legendary",
      grindstoneable: true,
      targets: ["bow", "crossbow"],
      conflicts: [],
      enabled: true,
    },
    {
      name: "Necrotic",
      description: "Wither skeletons have a higher chance to drop skulls.",
      "maximum-level": 4,
      obtaining: {
        table: true,
        villager: true,
        loot: true,
      },
      rarity: "rare",
      grindstoneable: true,
      targets: ["sword"],
      conflicts: ["looting"],
      enabled: true,
    },
    {
      name: "Netheric",
      description: "Increases damage dealt in the nether.",
      "maximum-level": 6,
      obtaining: {
        table: true,
        villager: true,
        loot: true,
      },
      rarity: "epic",
      grindstoneable: true,
      targets: ["bow", "crossbow"],
      conflicts: ["enderism"],
      enabled: true,
    },
    {
      name: "Nether Infusion",
      description: "Increases damage dealt in the nether.",
      "maximum-level": 6,
      obtaining: {
        table: true,
        villager: true,
        loot: true,
      },
      rarity: "epic",
      grindstoneable: true,
      targets: ["sword"],
      conflicts: ["end_infusion"],
      enabled: true,
    },
    {
      name: "Nocturnal",
      description: "Increases damage dealt at night.",
      "maximum-level": 6,
      obtaining: {
        table: true,
        villager: true,
        loot: true,
      },
      rarity: "rare",
      grindstoneable: true,
      targets: ["sword"],
      conflicts: ["diurnal"],
      enabled: true,
    },
    {
      name: "Optics",
      description: "Increases damage when further from target.",
      "maximum-level": 5,
      obtaining: {
        table: true,
        villager: true,
        loot: true,
      },
      rarity: "uncommon",
      grindstoneable: true,
      targets: ["bow", "crossbow"],
      conflicts: [],
      enabled: true,
    },
    {
      name: "Oxygenate",
      description: "Gain oxygen when breaking blocks underwater.",
      "maximum-level": 8,
      obtaining: {
        table: true,
        villager: true,
        loot: true,
      },
      rarity: "rare",
      grindstoneable: true,
      targets: ["pickaxe", "axe", "shovel", "hoe"],
      conflicts: [],
      enabled: true,
    },
    {
      name: "Pacify",
      description: "Increases damage against creepers.",
      "maximum-level": 5,
      obtaining: {
        table: true,
        villager: true,
        loot: true,
      },
      rarity: "common",
      targets: ["trident"],
      grindstoneable: true,
      conflicts: [
        "serrated",
        "bladed",
        "phantasm",
        "arachnid",
        "abattoir",
        "impaling",
      ],
      enabled: true,
    },
    {
      name: "Paladin",
      description: "Increases damage dealt when riding a horse.",
      "maximum-level": 3,
      obtaining: {
        table: true,
        villager: true,
        loot: true,
      },
      rarity: "epic",
      grindstoneable: true,
      targets: ["sword"],
      conflicts: [],
      enabled: true,
    },
    {
      name: "Paralyze",
      description: "Chance to give your attacker mining fatigue.",
      "maximum-level": 6,
      obtaining: {
        table: true,
        villager: true,
        loot: true,
      },
      rarity: "epic",
      grindstoneable: true,
      targets: ["shield"],
      conflicts: [],
      enabled: true,
    },
    {
      name: "Parasitic",
      description: "Heals a portion of damage dealt.",
      "maximum-level": 3,
      obtaining: {
        table: true,
        villager: true,
        loot: true,
      },
      rarity: "epic",
      targets: ["bow", "crossbow"],
      grindstoneable: true,
      conflicts: [],
      enabled: true,
    },
    {
      name: "Parry",
      description: "Reduces incoming damage when holding item.",
      "maximum-level": 4,
      obtaining: {
        table: true,
        villager: true,
        loot: true,
      },
      rarity: "epic",
      grindstoneable: true,
      targets: ["sword"],
      conflicts: [],
      enabled: true,
    },
    {
      name: "Phantasm",
      description: "Increases damage against undead mobs.",
      "maximum-level": 5,
      obtaining: {
        table: true,
        villager: true,
        loot: true,
      },
      rarity: "common",
      grindstoneable: true,
      targets: ["trident"],
      conflicts: [
        "serrated",
        "bladed",
        "arachnid",
        "pacify",
        "abattoir",
        "impaling",
      ],
      enabled: true,
    },
    {
      name: "Plasmic",
      description:
        "Increases damage dealt against opponents with diamond or netherite armor.",
      "maximum-level": 5,
      obtaining: {
        table: true,
        villager: true,
        loot: true,
      },
      rarity: "legendary",
      grindstoneable: true,
      targets: ["sword"],
      conflicts: ["voltage"],
      enabled: true,
    },
    {
      name: "Protector",
      description: "Prevents damaging your own pets.",
      "maximum-level": 1,
      obtaining: {
        table: true,
        villager: true,
        loot: true,
      },
      rarity: "uncommon",
      grindstoneable: true,
      targets: ["sword", "axe"],
      conflicts: [],
      enabled: true,
    },
    {
      name: "Proximity",
      description: "Increases damage when closer to opponent.",
      "maximum-level": 5,
      obtaining: {
        table: true,
        villager: true,
        loot: true,
      },
      rarity: "rare",
      grindstoneable: true,
      targets: ["sword"],
      conflicts: [],
      enabled: true,
    },
    {
      name: "Puncture",
      description: "Trident deals additional damage to shelled mobs.",
      "maximum-level": 6,
      obtaining: {
        table: true,
        villager: true,
        loot: true,
      },
      rarity: "rare",
      grindstoneable: true,
      targets: ["trident"],
      conflicts: [],
      enabled: true,
    },
    {
      name: "Quadrilateralism",
      description: "Increases damage dealt against slimes and magma cubes.",
      "maximum-level": 7,
      obtaining: {
        table: true,
        villager: true,
        loot: true,
      },
      rarity: "rare",
      grindstoneable: true,
      targets: ["bow", "crossbow"],
      conflicts: [],
      enabled: true,
    },
    {
      name: "Radiance",
      description: "Causes entities to glow near where arrow lands.",
      "maximum-level": 4,
      obtaining: {
        table: true,
        villager: true,
        loot: true,
      },
      rarity: "epic",
      grindstoneable: true,
      targets: ["bow", "crossbow"],
      conflicts: [],
      enabled: true,
    },
    {
      name: "Rage",
      description: "Chance of angering nearby monsters towards your opponent.",
      "maximum-level": 5,
      obtaining: {
        table: true,
        villager: true,
        loot: true,
      },
      rarity: "epic",
      grindstoneable: true,
      targets: ["bow"],
      conflicts: [],
      enabled: true,
    },
    {
      name: "Rapid",
      description: "Increases bow pull speed.",
      "maximum-level": 6,
      obtaining: {
        table: true,
        villager: true,
        loot: true,
      },
      rarity: "uncommon",
      grindstoneable: true,
      targets: ["bow"],
      conflicts: [],
      enabled: true,
    },
    {
      name: "Reaper",
      description: "Chance to prevent your opponents soulbound from working.",
      "maximum-level": 3,
      obtaining: {
        table: true,
        villager: false,
        loot: false,
      },
      rarity: "legendary",
      grindstoneable: true,
      targets: ["sword", "axe"],
      conflicts: [],
      enabled: false,
    },
    {
      name: "Rebounding",
      description: "Deal knockback to entities that attack you.",
      "maximum-level": 2,
      obtaining: {
        table: true,
        villager: true,
        loot: true,
      },
      rarity: "epic",
      grindstoneable: true,
      targets: ["helmet", "chestplate", "leggings", "boots"],
      conflicts: [],
      enabled: true,
    },
    {
      name: "Reel",
      description: "Pulls entities towards you.",
      "maximum-level": 2,
      obtaining: {
        table: true,
        villager: true,
        loot: true,
      },
      rarity: "epic",
      grindstoneable: true,
      targets: ["rod"],
      conflicts: [],
      enabled: true,
    },
    {
      name: "Reinforcement",
      description: "Reduces incoming damage.",
      "maximum-level": 4,
      obtaining: {
        table: true,
        villager: true,
        loot: true,
      },
      rarity: "common",
      grindstoneable: true,
      targets: ["elytra"],
      conflicts: [],
      enabled: true,
    },
    {
      name: "Rejuvenation",
      description: "Increases natural regeneration speed",
      "maximum-level": 2,
      obtaining: {
        table: true,
        villager: true,
        loot: true,
      },
      rarity: "legendary",
      grindstoneable: true,
      targets: ["helmet", "chestplate", "leggings", "boots"],
      conflicts: [],
      type: "normal",
      enabled: true,
    },
    {
      name: "Replenish",
      description: "Automatically replants crops.",
      "maximum-level": 1,
      obtaining: {
        table: true,
        villager: true,
        loot: true,
      },
      rarity: "epic",
      grindstoneable: true,
      targets: ["hoe"],
      conflicts: [],
      enabled: true,
    },
    {
      name: "Respirator",
      description: "Reduces dragon breath damage.",
      "maximum-level": 6,
      obtaining: {
        table: true,
        villager: true,
        loot: true,
      },
      rarity: "rare",
      grindstoneable: true,
      targets: ["helmet"],
      conflicts: [],
      enabled: true,
    },
    {
      name: "Revenant",
      description: "Increases damage against undead mobs.",
      "maximum-level": 5,
      obtaining: {
        table: true,
        villager: true,
        loot: true,
      },
      rarity: "common",
      grindstoneable: true,
      targets: ["bow"],
      conflicts: ["power", "force", "insecticide", "slaughter", "settle"],
      enabled: true,
    },
    // Unorder
    {
      name: "Sating",
      description: "Reduces hunger loss .",
      enabled: true,
      obtaining: {
        table: true,
        villager: true,
        loot: true,
      },
      rarity: "epic",
      targets: ["helmet"],
      grindstoneable: true,
      conflicts: [],
      "maximum-level": 6,
    },
    {
      name: "Serrated",
      description: "Trident deals additional damage.",
      enabled: true,
      obtaining: {
        table: true,
        villager: true,
        loot: true,
      },
      rarity: "common",
      targets: ["trident"],
      grindstoneable: true,
      conflicts: [
        "bladed",
        "phantasm",
        "arachnid",
        "pacify",
        "abattoir",
        "impaling",
      ],
      "maximum-level": 5,
    },
    {
      name: "Settle",
      description: "Increases damage against creepers.",
      enabled: true,
      obtaining: {
        table: true,
        villager: true,
        loot: true,
      },
      rarity: "common",
      targets: ["bow"],
      grindstoneable: true,
      conflicts: ["power", "force", "revenant", "slaughter", "insecticide"],
      "maximum-level": 5,
    },
    {
      name: "Shockwave",
      description: "Damages entities that arrows fly near.",
      enabled: false,
      obtaining: {
        table: true,
        villager: true,
        loot: true,
      },
      rarity: "rare",
      targets: ["bow"],
      grindstoneable: true,
      conflicts: [],
      "maximum-level": 3,
    },
    {
      name: "Shot Assist",
      description: "Deal more damage with arrows while wearing.",
      enabled: true,
      obtaining: {
        table: true,
        villager: true,
        loot: true,
      },
      rarity: "legendary",
      targets: ["helmet", "chestplate", "leggings", "boots"],
      grindstoneable: true,
      conflicts: [],
      "maximum-level": 6,
    },
    {
      name: "Sickening",
      description: "Chance of nauseating your opponent.",
      enabled: true,
      obtaining: {
        table: true,
        villager: true,
        loot: true,
      },
      rarity: "legendary",
      targets: ["bow", "crossbow"],
      grindstoneable: true,
      conflicts: [],
      "maximum-level": 2,
    },
    {
      name: "Slaughter",
      description: "Increases damage against passive mobs.",
      enabled: true,
      obtaining: {
        table: true,
        villager: true,
        loot: true,
      },
      rarity: "common",
      targets: ["bow"],
      grindstoneable: true,
      conflicts: ["power", "force", "revenant", "insecticide", "settle"],
      "maximum-level": 5,
    },
    {
      name: "Slicing",
      description: "Damages entities when flown through.",
      enabled: true,
      obtaining: {
        table: true,
        villager: true,
        loot: true,
      },
      rarity: "common",
      targets: ["elytra"],
      grindstoneable: true,
      conflicts: [],
      "maximum-level": 8,
    },
    {
      name: "Spearfishing",
      description: "Chance of dropping fish when tridenting water.",
      enabled: true,
      obtaining: {
        table: true,
        villager: true,
        loot: true,
      },
      rarity: "rare",
      targets: ["trident"],
      grindstoneable: true,
      conflicts: [],
      "maximum-level": 6,
    },
    {
      name: "Spiked",
      description: "Hooking onto an entity will damage it.",
      enabled: true,
      obtaining: {
        table: true,
        villager: true,
        loot: true,
      },
      rarity: "common",
      targets: ["rod"],
      grindstoneable: true,
      conflicts: ["harpoon"],
      "maximum-level": 3,
    },
    {
      name: "Splash",
      description:
        "Damages entities near where trident lands but does not drop experience.",
      enabled: true,
      obtaining: {
        table: true,
        villager: true,
        loot: true,
      },
      rarity: "epic",
      targets: ["trident"],
      grindstoneable: true,
      conflicts: ["wisdom"],
      "maximum-level": 4,
    },
    {
      name: "Stab",
      description: "Increases melee trident damage.",
      enabled: true,
      obtaining: {
        table: true,
        villager: true,
        loot: true,
      },
      rarity: "rare",
      targets: ["trident"],
      grindstoneable: true,
      conflicts: [],
      "maximum-level": 5,
    },
    {
      name: "Stalwart",
      description:
        "Chance to get resistance for a short time when taking damage.",
      enabled: true,
      obtaining: {
        table: true,
        villager: true,
        loot: true,
      },
      rarity: "epic",
      targets: ["helmet", "chestplate", "leggings", "boots"],
      grindstoneable: true,
      conflicts: [],
      "maximum-level": 3,
    },
    {
      name: "Stamina",
      description: "Decreases hunger loss while sprinting.",
      enabled: true,
      obtaining: {
        table: true,
        villager: true,
        loot: true,
      },
      rarity: "epic",
      targets: ["boots"],
      grindstoneable: true,
      conflicts: [],
      "maximum-level": 4,
    },
    {
      name: "Stone Switcher",
      description: "Chance for stone to drop as variants.",
      enabled: true,
      obtaining: {
        table: true,
        villager: true,
        loot: true,
      },
      rarity: "epic",
      targets: ["pickaxe"],
      grindstoneable: true,
      conflicts: ["transfuse", "silk_touch"],
      "maximum-level": 6,
    },
    {
      name: "Stray Aspect",
      description: "Chance of slowing your opponent.",
      enabled: true,
      obtaining: {
        table: true,
        villager: true,
        loot: true,
      },
      rarity: "rare",
      targets: ["sword"],
      grindstoneable: true,
      conflicts: [],
      "maximum-level": 6,
    },
    {
      name: "Succession",
      description: "Shoots multiple arrows in a burst.",
      enabled: true,
      obtaining: {
        table: true,
        villager: true,
        loot: true,
      },
      rarity: "legendary",
      targets: ["bow"],
      grindstoneable: true,
      conflicts: ["tripleshot", "pentashot", "buckshot"],
      "maximum-level": 4,
    },
    {
      name: "Supercritical",
      description: "Chance to deal extreme damage.",
      enabled: true,
      obtaining: {
        table: true,
        villager: true,
        loot: true,
      },
      rarity: "legendary",
      targets: ["sword"],
      grindstoneable: true,
      conflicts: [],
      "maximum-level": 3,
    },
    {
      name: "Sycophant",
      description: "Heals a portion of damage blocked.",
      enabled: true,
      obtaining: {
        table: true,
        villager: true,
        loot: true,
      },
      rarity: "epic",
      targets: ["shield"],
      grindstoneable: true,
      conflicts: [],
      "maximum-level": 3,
    },
    {
      name: "Tectonic",
      description: "Damages nearby entities when taking fall damage.",
      enabled: true,
      obtaining: {
        table: true,
        villager: true,
        loot: true,
      },
      rarity: "epic",
      targets: ["boots"],
      grindstoneable: true,
      conflicts: ["feather_falling"],
      "maximum-level": 2,
    },
    {
      name: "Telekinesis",
      description: "Drops and xp go directly into your inventory.",
      enabled: false,
      obtaining: {
        table: true,
        villager: true,
        loot: true,
      },
      rarity: "uncommon",
      targets: [
        "pickaxe",
        "axe",
        "shovel",
        "hoe",
        "sword",
        "bow",
        "crossbow",
        "trident",
      ],
      grindstoneable: true,
      conflicts: [],
      "maximum-level": 1,
    },
    {
      name: "Thor",
      description: "Chance of striking lightning on your opponent.",
      enabled: true,
      obtaining: {
        table: true,
        villager: true,
        loot: true,
      },
      rarity: "rare",
      targets: ["sword"],
      grindstoneable: true,
      conflicts: [],
      "maximum-level": 6,
    },
    {
      name: "Thrive",
      description: "Increases maximum health.",
      enabled: true,
      obtaining: {
        table: true,
        villager: true,
        loot: true,
      },
      rarity: "epic",
      targets: ["helmet", "chestplate", "leggings", "boots"],
      grindstoneable: true,
      conflicts: ["prosperity"],
      "maximum-level": 2,
    },
    {
      name: "Tornado",
      description: "Knocks your opponent into the air.",
      enabled: true,
      obtaining: {
        table: true,
        villager: true,
        loot: true,
      },
      rarity: "epic",
      targets: ["sword", "axe"],
      grindstoneable: true,
      conflicts: ["knockback", "grapple", "annihilate"],
      "maximum-level": 2,
    },
    {
      name: "Toxic",
      description: "Chance to apply poison to your opponent.",
      enabled: true,
      obtaining: {
        table: true,
        villager: true,
        loot: true,
      },
      rarity: "rare",
      targets: ["sword"],
      grindstoneable: true,
      conflicts: [],
      "maximum-level": 2,
    },
    {
      name: "Transfuse",
      description: "Chance for stone to drop as random ore.",
      enabled: true,
      obtaining: {
        table: true,
        villager: true,
        loot: true,
      },
      rarity: "legendary",
      targets: ["pickaxe"],
      grindstoneable: true,
      conflicts: ["stone_switcher", "silk_touch"],
      "maximum-level": 7,
    },
    {
      name: "Tripleshot",
      description: "Shoots 3 arrows.",
      enabled: true,
      obtaining: {
        table: true,
        villager: true,
        loot: true,
      },
      rarity: "legendary",
      targets: ["bow"],
      grindstoneable: true,
      conflicts: ["succession", "pentashot", "buckshot"],
      "maximum-level": 1,
    },
    {
      name: "Vampire Aspect",
      description: "Chance to apply wither to your opponent.",
      enabled: true,
      obtaining: {
        table: true,
        villager: true,
        loot: true,
      },
      rarity: "rare",
      targets: ["sword"],
      grindstoneable: true,
      conflicts: [],
      "maximum-level": 2,
    },
    {
      name: "Vein",
      description: "Mine blocks in a vein.",
      enabled: false,
      obtaining: {
        table: true,
        villager: true,
        loot: true,
      },
      rarity: "legendary",
      targets: ["pickaxe"],
      grindstoneable: true,
      "maximum-level": 5,
      conflicts: ["drill", "blast_mining"],
    },
    {
      name: "Venom",
      description: "Chance of withering your opponent.",
      enabled: true,
      obtaining: {
        table: true,
        villager: true,
        loot: true,
      },
      rarity: "epic",
      targets: ["bow", "crossbow"],
      grindstoneable: true,
      conflicts: [],
      "maximum-level": 6,
    },
    {
      name: "Void Affinity",
      description: "Increases damage dealt in the end.",
      enabled: true,
      obtaining: {
        table: true,
        villager: true,
        loot: true,
      },
      rarity: "epic",
      targets: ["trident"],
      grindstoneable: true,
      conflicts: ["netheric"],
      "maximum-level": 5,
    },
    {
      name: "Voltage",
      description:
        "Increases damage dealt against opponents with iron, gold, or chain armor.",
      enabled: false,
      obtaining: {
        table: true,
        villager: true,
        loot: true,
      },
      rarity: "legendary",
      targets: ["sword"],
      grindstoneable: true,
      conflicts: ["plasmic"],
      "maximum-level": 5,
    },
    {
      name: "Water Affinity",
      description: "Increases damage dealt when in water.",
      enabled: true,
      obtaining: {
        table: true,
        villager: true,
        loot: true,
      },
      rarity: "epic",
      targets: ["sword"],
      grindstoneable: true,
      conflicts: ["fire_affinity"],
      "maximum-level": 7,
    },
    {
      name: "Water Aspect",
      description: "Increases damage dealt against fiery mobs.",
      enabled: true,
      obtaining: {
        table: true,
        villager: true,
        loot: true,
      },
      rarity: "rare",
      targets: ["sword", "axe"],
      grindstoneable: true,
      conflicts: ["fire_aspect"],
      "maximum-level": 2,
    },
    {
      name: "Weakening",
      description: "Increases subsequent damage dealt to opponent.",
      enabled: true,
      obtaining: {
        table: true,
        villager: true,
        loot: true,
      },
      rarity: "epic",
      targets: ["sword"],
      grindstoneable: true,
      conflicts: [],
      "maximum-level": 4,
    },
    {
      name: "Wisdom",
      description: "Increases dropped experience.",
      enabled: true,
      obtaining: {
        table: true,
        villager: true,
        loot: true,
      },
      rarity: "uncommon",
      targets: [
        "sword",
        "axe",
        "pickaxe",
        "shovel",
        "hoe",
        "bow",
        "crossbow",
        "trident",
      ],
      grindstoneable: true,
      conflicts: ["splash", "intellect"],
      "maximum-level": 3,
    },
    {
      name: "Wood Switcher",
      description: "Breaking logs have a Chance to drop as other logs.",
      enabled: true,
      obtaining: {
        table: true,
        villager: true,
        loot: true,
      },
      rarity: "epic",
      targets: ["axe"],
      grindstoneable: true,
      conflicts: ["silk_touch"],
      "maximum-level": 6,
    },
    {
      name: "Wound",
      description:
        "Chance to cause your opponent to bleed, damaging them repeatedly.",
      enabled: true,
      obtaining: {
        table: true,
        villager: true,
        loot: true,
      },
      rarity: "legendary",
      targets: ["bow", "crossbow"],
      grindstoneable: true,
      conflicts: [],
      "maximum-level": 7,
    },
    {
      name: "Zeus",
      description: "Chance to strike lightning on your opponent.",
      enabled: true,
      obtaining: {
        table: true,
        villager: true,
        loot: true,
      },
      rarity: "epic",
      targets: ["bow", "crossbow"],
      grindstoneable: true,
      conflicts: [],
      "maximum-level": 6,
    },
    // **************************************************** //
    // Special
    // **************************************************** //
    {
      name: "Aiming",
      description: "Arrows hone in on your target.",
      "maximum-level": 5,
      obtaining: {
        table: true,
        villager: true,
        loot: true,
      },
      rarity: "special",
      grindstoneable: true,
      targets: ["bow"],
      conflicts: ["silk_touch"],
      type: "special",
      enabled: true,
    },
    {
      name: "Annihilate",
      description: "Extreme Knockback.",
      "maximum-level": 2,
      obtaining: {
        table: true,
        villager: true,
        loot: true,
      },
      rarity: "special",
      grindstoneable: true,
      targets: ["sword", "axe"],
      conflicts: ["knockback", "tornado", "grapple"],
      type: "special",
      enabled: true,
    },
    {
      name: "Bladed",
      description: "Trident deals extreme additional damage.",
      "maximum-level": 5,
      obtaining: {
        table: true,
        villager: true,
        loot: true,
      },
      rarity: "veryspecial",
      grindstoneable: true,
      targets: ["trident"],
      conflicts: [
        "impaling",
        "serrated",
        "phantasm",
        "arachnid",
        "pacify",
        "abattoir",
      ],
      type: "special",
      enabled: true,
    },
    {
      name: "Bolt",
      description: "Chance of striking powerful lightning on your opponent.",
      "maximum-level": 4,
      obtaining: {
        table: true,
        villager: true,
        loot: true,
      },
      rarity: "special",
      grindstoneable: true,
      targets: ["sword"],
      conflicts: [],
      type: "special",
      enabled: false,
    },
    {
      name: "Carve",
      description: "Heavily damage all entities around attacked entity.",
      "maximum-level": 8,
      obtaining: {
        table: true,
        villager: true,
        loot: true,
      },
      rarity: "special",
      grindstoneable: true,
      targets: ["axe"],
      conflicts: ["cleave"],
      type: "special",
      enabled: true,
    },
    {
      name: "Confusion",
      description: "Chance to shuffle your opponents hotbar.",
      "maximum-level": 4,
      obtaining: {
        table: true,
        villager: true,
        loot: true,
      },
      rarity: "special",
      grindstoneable: true,
      targets: ["sword"],
      conflicts: [],
      type: "special",
      enabled: true,
    },
    {
      name: "Energizing",
      description: "Receive a short burst of haste after breaking a block.",
      "maximum-level": 3,
      obtaining: {
        table: true,
        villager: true,
        loot: true,
      },
      rarity: "special",
      grindstoneable: true,
      targets: ["pickaxe", "axe", "shovel", "hoe"],
      conflicts: [],
      type: "special",
      enabled: true,
    },
    {
      name: "Force",
      description: "Massively increases arrow damage.",
      "maximum-level": 4,
      obtaining: {
        table: true,
        villager: true,
        loot: true,
      },
      rarity: "veryspecial",
      grindstoneable: true,
      targets: ["bow"],
      conflicts: ["power", "revenant", "insecticide", "slaughter", "settle"],
      type: "special",
      enabled: true,
    },
    {
      name: "Frenzy",
      description: "Gives strength after killing an entity.",
      "maximum-level": 3,
      obtaining: {
        table: true,
        villager: true,
        loot: true,
      },
      rarity: "special",
      grindstoneable: true,
      targets: ["sword"],
      conflicts: [],
      type: "special",
      enabled: true,
    },
    {
      name: "Harpoon",
      description: "Hooking onto an entity will heavily damage it.",
      "maximum-level": 3,
      obtaining: {
        table: true,
        villager: true,
        loot: true,
      },
      rarity: "special",
      grindstoneable: true,
      targets: ["rod"],
      conflicts: ["spiked"],
      type: "special",
      enabled: true,
    },
    {
      name: "Indestructibility",
      description: "Massively increases item durability.",
      "maximum-level": 3,
      obtaining: {
        table: true,
        villager: true,
        loot: true,
      },
      rarity: "special",
      grindstoneable: true,
      targets: ["all"],
      conflicts: ["unbreaking"],
      type: "special",
      enabled: true,
    },
    {
      name: "Instability",
      description: "Explosive arrows.",
      "maximum-level": 3,
      obtaining: {
        table: true,
        villager: true,
        loot: true,
      },
      rarity: "special",
      grindstoneable: true,
      targets: ["bow", "crossbow"],
      conflicts: [],
      type: "special",
      enabled: true,
    },
    {
      name: "Intellect",
      description: "Massively increases dropped experience.",
      "maximum-level": 3,
      obtaining: {
        table: true,
        villager: true,
        loot: true,
      },
      rarity: "special",
      grindstoneable: true,
      targets: [
        "bow",
        "crossbow",
        "trident",
        "pickaxe",
        "axe",
        "shovel",
        "hoe",
        "sword",
      ],
      conflicts: ["splash", "wisdom"],
      type: "special",
      enabled: true,
    },
    {
      name: "Life Steal",
      description: "Heals a large portion of damage dealt.",
      "maximum-level": 3,
      obtaining: {
        table: true,
        villager: true,
        loot: true,
      },
      rarity: "special",
      grindstoneable: true,
      targets: ["sword", "axe"],
      conflicts: ["leeching"],
      type: "special",
      enabled: true,
    },
    {
      name: "Pentashot",
      description: "Shoots 5 arrows.",
      "maximum-level": 1,
      obtaining: {
        table: true,
        villager: true,
        loot: true,
      },
      rarity: "special",
      grindstoneable: true,
      targets: ["bow"],
      conflicts: ["succession", "tripleshot", "buckshot"],
      type: "special",
      enabled: true,
    },
    {
      name: "Preservation",
      description: "Massively reduces incoming damage.",
      "maximum-level": 4,
      obtaining: {
        table: true,
        villager: true,
        loot: true,
      },
      rarity: "special",
      grindstoneable: true,
      targets: ["helmet", "chestplate", "leggings", "boots"],
      conflicts: [
        "protection",
        "fire_protection",
        "projectile_protection",
        "blast_protection",
      ],
      type: "special",
      enabled: true,
    },
    {
      name: "Prosperity",
      description: "Massively increases maximum health.",
      "maximum-level": 3,
      obtaining: {
        table: true,
        villager: true,
        loot: true,
      },
      rarity: "veryspecial",
      grindstoneable: true,
      targets: ["helmet", "chestplate", "leggings", "boots"],
      conflicts: ["thrive"],
      type: "special",
      enabled: true,
    },
    {
      name: "Razor",
      description: "Massively increases damage dealt.",
      "maximum-level": 6,
      obtaining: {
        table: true,
        villager: true,
        loot: true,
      },
      rarity: "veryspecial",
      grindstoneable: true,
      targets: ["sword"],
      conflicts: [
        "sharpness",
        "smite",
        "bane_of_arthropods",
        "defusion",
        "butchering",
        "ender_slayer",
        "introversion",
      ],
      type: "special",
      enabled: true,
    },
    {
      name: "Repairing",
      description: "Automatically repairs items when not held.",
      "maximum-level": 3,
      obtaining: {
        table: false,
        villager: true,
        loot: true,
      },
      rarity: "veryspecial",
      grindstoneable: true,
      targets: ["all"],
      conflicts: ["mending", "decay_curse"],
      type: "special",
      enabled: true,
    },
    {
      name: "Soulbound",
      description: "Keep this item on death.",
      "maximum-level": 1,
      obtaining: {
        table: true,
        villager: true,
        loot: true,
      },
      rarity: "special",
      grindstoneable: true,
      targets: ["all"],
      conflicts: [],
      type: "special",
      enabled: true,
    },
    {
      name: "Spring",
      description: "Increases jump height and distance.",
      "maximum-level": 3,
      obtaining: {
        table: true,
        villager: true,
        loot: true,
      },
      rarity: "special",
      grindstoneable: true,
      targets: ["boots"],
      conflicts: [],
      type: "special",
      enabled: true,
    },
    {
      name: "Streamlining",
      description: "Increases movement speed.",
      "maximum-level": 8,
      obtaining: {
        table: true,
        villager: true,
        loot: true,
      },
      rarity: "special",
      grindstoneable: true,
      targets: ["boots"],
      conflicts: [],
      type: "special",
      enabled: true,
    },
    {
      name: "Volatile",
      description: "Chance to have explosive sword attacks.",
      "maximum-level": 2,
      obtaining: {
        table: true,
        villager: true,
        loot: true,
      },
      rarity: "special",
      grindstoneable: true,
      targets: ["sword"],
      conflicts: [],
      type: "special",
      enabled: false,
    },
    // **************************************************** //
    // Spell
    // **************************************************** //
    {
      name: "Ascend",
      description: "Levitates you into the air.",
      "maximum-level": 2,
      obtaining: {
        table: true,
        villager: true,
        loot: true,
      },
      rarity: "legendary",
      grindstoneable: true,
      targets: ["sword"],
      conflicts: [],
      type: "spell",
      enabled: true,
    },
    {
      name: "Charge",
      description: "Launches you in the direction you're looking.",
      "maximum-level": 6,
      obtaining: {
        table: true,
        villager: true,
        loot: true,
      },
      rarity: "legendary",
      grindstoneable: true,
      targets: ["sword"],
      conflicts: [],
      type: "spell",
      enabled: true,
    },
    {
      name: "Dynamite",
      description: "Mines blocks in a large area.",
      "maximum-level": 2,
      obtaining: {
        table: true,
        villager: true,
        loot: true,
      },
      rarity: "legendary",
      grindstoneable: true,
      targets: ["pickaxe"],
      conflicts: [],
      type: "spell",
      enabled: false,
    },
    {
      name: "Missile",
      description: "Shoots a wither skull.",
      "maximum-level": 3,
      obtaining: {
        table: true,
        villager: true,
        loot: true,
      },
      rarity: "epic",
      grindstoneable: true,
      targets: ["sword", "axe"],
      conflicts: [],
      type: "spell",
      enabled: false,
    },
    {
      name: "Quake",
      description: "Damages all nearby entities.",
      "maximum-level": 3,
      obtaining: {
        table: true,
        villager: true,
        loot: true,
      },
      rarity: "epic",
      grindstoneable: true,
      targets: ["sword"],
      conflicts: [],
      type: "spell",
      enabled: false,
    },
    {
      name: "Vitalize",
      description: "Puts you back on max health.",
      "maximum-level": 1,
      obtaining: {
        table: true,
        villager: true,
        loot: true,
      },
      rarity: "special",
      grindstoneable: true,
      targets: ["sword", "axe", "pickaxe", "shovel"],
      conflicts: [],
      type: "spell",
      enabled: true,
    },
  ],

  rarity: {
    common: {
      "table-probability": 30,
      "minimum-level": 1,
      "villager-probability": 10.5,
      "loot-probability": 12,
      color: "#ababab",
    },
    uncommon: {
      "table-probability": 20,
      "minimum-level": 5,
      "villager-probability": 9,
      "loot-probability": 16,
      color: "#53ff55",
    },
    rare: {
      "table-probability": 20,
      "minimum-level": 15,
      "villager-probability": 7.5,
      "loot-probability": 18,
      color: "#5856ff",
    },
    epic: {
      "table-probability": 10,
      "minimum-level": 16,
      "villager-probability": 6,
      "loot-probability": 20,
      color: "#ff56fc",
    },
    special: {
      "table-probability": 2,
      "minimum-level": 30,
      "villager-probability": 3,
      "loot-probability": 5,
      color: "#8d0bb5",
    },
    veryspecial: {
      "table-probability": 1,
      "minimum-level": 30,
      "villager-probability": 1.5,
      "loot-probability": 2,
      color: "#ad0101",
    },
    legendary: {
      "table-probability": 8,
      "minimum-level": 20,
      "villager-probability": 4.5,
      "loot-probability": 15,
      color: "#ffac03",
    },
    artifact: {
      "table-probability": 5,
      "minimum-level": 1,
      "villager-probability": 9,
      "loot-probability": 5,
      color: "#555555",
    },
  },

  filters: {
    rarities: "none",
    allTargets: "none",
    artifacts: false,
    curses: false,
  },

  loading: false,
};






const EnchantsReducer = (state = initstates, action) => {
  switch (action.type) {
    case "loading":
      return {
        ...state,
        loading: true,
      };

    case "updateFilterRarity":
      return {
        ...state,
        filters: {
          rarities: action.payload,
          allTargets: state.filters["allTargets"],
          artifacts:
            action.payload === "artifact" ? true : state.filters["artifacts"],
          curses: state.filters["curses"],
        },
      };

    case "updateFilterTarget":
      return {
        ...state,
        filters: {
          rarities: state.filters["rarities"],
          allTargets: action.payload,
          artifacts: state.filters["artifacts"],
          curses: state.filters["curses"],
        },
      };

    case "avilableArtifacts":
      return {
        ...state,
        filters: {
          rarities:
            state.filters["rarities"] === "artifact" &&
            state.filters["artifacts"]
              ? "none"
              : state.filters["rarities"],
          allTargets: state.filters["allTargets"],
          artifacts: state.filters["artifacts"] ? false : true,
          curses: state.filters["curses"],
        },
      };

    case "avilableCurses":
      return {
        ...state,
        filters: {
          rarities: state.filters["rarities"],
          allTargets: state.filters["allTargets"],
          artifacts: state.filters["artifacts"],
          curses: state.filters["curses"] ? false : true,
        },
      };

    default:
      return state;
  }
};

export default EnchantsReducer;
